config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top' 
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'

  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :authenticate_user!, only: [:index, :show, :edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
		@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
	end
	
  def edit
		@user = User.find(params[:id])
		unless @user == current_user
			redirect_to user_path(current_user)
		end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
		else
  		render "edit"
  	end
	end
	
	def following
		@user  = User.find(params[:id])
		@users = @user.followings
		render 'show_follow'
	end

	def followers
		@user  = User.find(params[:id])
		@users = @user.followers
		render 'show_follower'
	end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
	 	end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="6"></th>
				</tr>
			</thead>

			<tbody>
				<% users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					<td>
					<% unless current_user == user %>
						<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
								<%= hidden_field_tag :follow_id, user.id %>
								<%= f.submit 'フォローをはずす', class: 'btn btn-danger btn-block' %>
							<% end %>
						<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
								<%= hidden_field_tag :follow_id, user.id %>
								<%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
							<% end %>
						<% end %>
					<% end %>
					</td>
					<td>
						<a href="<%= user_follows_path(user) %>">
							<%= user.followings.count %>
						</a>フォロー
					</td>
					<td>
						<a href="<%= user_followers_path(user) %>">
							<%= user.followers.count %>
						</a>フォロワー
					</td>
				<% end %>
				</tr>
			</tbody>
		</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', class: "attachment user profile_image", fallback: "no_image.jpg", alt: "profile_image" %></tr>
	<tbody>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>Follow</th>
			<th>
				<a href="<%= user_follows_path(user) %>">
					<%= user.followings.count %>
				</a>
			</th>
		</tr>
		<tr>
			<th>Follower</th>
			<th>
				<a href="<%= user_followers_path(user) %>">
					<%= user.followers.count %>
				</a>
			</th>
		</tr>
	</tbody>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
  <%= render 'layouts/errors', model: @user %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
    <%= render 'index',users: @users %>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<div class="row follow-btn">
			<%= render 'relationships/follow_button', user: @user %>
		</div>
		<!--同コントローラーのviewで表示ならusersは省略可 -->
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->
	</div>