config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top' 
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'

  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!


  def show
		@book = Book.find(params[:id])
		@newbook = Book.new
		@book_comment = BookComment.new
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
		@book = Book.new
  end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
		@book = Book.find(params[:id])
		unless @book.user.id == current_user.id
			redirect_to "/books"            
		end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th>Comments</th>
					<th>Good</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
        <% books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<i class="glyphicon glyphicon-comment"></i>
						<%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
					</td>
					<% if book.favorited_by?(current_user) %>
						<td>
							<%= button_to book_favorites_path(book), method: :delete, style: "background-color:white; border: none;" do %>
								<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></i>
							<%= book.favorites.count %>いいね！
							<% end %>
						</td>
					<% else %>
						<td>
							<%= button_to book_favorites_path(book), method: :post, style: "background-color:white; border: none;" do %>
							<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
							<%= book.favorites.count %> いいね！
							<% end %>
						</td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<%= render 'layouts/errors', model: @book %>

<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %> / 
<%= link_to "Back", books_path, class: "back" %>

</div>
    <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', model: @book %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>

		<!--books一覧 -->
		<%= render 'index', books: @books %>
		<!--books一覧 -->

	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user_id) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<% if @book.user == current_user %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
					<td>  
						<i class="glyphicon glyphicon-comment"></i>
  					<a href="#comments"><%= @book.book_comments.count %></a>
					</td>
					<% if @book.favorited_by?(current_user) %>
						<td>
							<%= button_to book_favorites_path(@book), method: :delete, style: "background-color:white; border: none;" do %>
								<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></i>
							<%= @book.favorites.count %>いいね！
							<% end %>
						</td>
					<% else %>
						<td>
							<%= button_to book_favorites_path(@book), method: :post, style: "background-color:white; border: none;" do %>
							<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
							<%= @book.favorites.count %> いいね！
							<% end %>
						</td>
					<% end %>
				</tr>
		</table>
		<div class="comment-list bt style-2" id="comments">
			<div class="float-wrapper">
				<h2 class="comment-count"><%= @book.book_comments.count %>件コメント</h2>
			</div>
		</div>
		<table class="table">
			<% @book.book_comments.each do |book_comment| %>
				<tr>
					<td><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td>
						<a href="#" class="link-author"><%= book_comment.user.name %></a></td>
					<td>
						<%= book_comment.comment %>
					</td>
					<td>
						<%= book_comment.created_at.strftime('%Y/%m/%d') %>
					</td>
					<% if book_comment.user == current_user %>
						<td>
							<%= link_to "delete", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
						</td>
					<% end %>
				</tr>
			<% end %>
		</table>
		<%= form_for [@book, @book_comment] do |f| %>
			<div class="row">
				<div class="col-xs-12">
					<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
				</div>
			</div>
			<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
		<% end %>
	</div>
</div>