config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top' 
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'

  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!,only: [:after_sign_in_path_for, :after_sign_out_path_for ]
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path  
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction])

  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!


  def show
		@book = Book.find(params[:id])
		@newbook = Book.new
		@book_comment = BookComment.new
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
		@book = Book.new
  end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
		@book = Book.find(params[:id])
		unless @book.user.id == current_user.id
			redirect_to "/books"            
		end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    if @range == '1'
      @user = search_user(search,word)
    elsif @range == '2'
      @book = search_book(search,word)
    elsif @range == '0'
      redirect_back(fallback_location: root_path)
      flash[:notice] = "「User」か「Book」を選んでください。"
    end
  end

  private

  def search_user(search,word)
    if search == "forward_match"
      User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      User.where("#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?","%#{word}%")
    else
      User.all
    end
  end

  def search_book(search,word)
    if search == "forward_match"
      Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      Book.where("#{word}")
    elsif search == "partial_match"
      Book.where("title LIKE?","%#{word}%")
    else
      Book.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :authenticate_user!, only: [:index, :show, :edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
		@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
	end
	
  def edit
		@user = User.find(params[:id])
		unless @user == current_user
			redirect_to user_path(current_user)
		end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
		else
  		render "edit"
  	end
	end
	
	def following
		@user  = User.find(params[:id])
		@users = @user.followings
		render 'show_follow'
	end

	def followers
		@user  = User.find(params[:id])
		@users = @user.followers
		render 'show_follower'
	end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
	 	end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
	<div id="error_explanation">
      <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h3>
		<ul>
			<% model.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    
    <%# 検索欄 %>
    <div class="search-bar">
      <% if user_signed_in? %>
        <div class="container">
          <%= form_tag(search_path, method: :get) do %>
            <div class="input-group nav navbar-nav navbar-right">
              <%= text_field_tag (:word),'', class: "form-control", placeholder: "ユーザー名か本のタイトルで検索できます" %>
                <span class="input-group-btn">
                  <%= select_tag 'range' ,options_for_select([['--選択してください--', '0'], ['User', '1'], ['Book', '2']]), class: "btn btn-default dropdown-toggle" %>
                  <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]), class: "btn btn-default dropdown-toggle" %>
                  <%= submit_tag "検索", :name => nil, class: "btn btn-primary" %>
                </span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%# 検索欄 %>

    <div class="body">
      <div class="container">
        <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>